
logging.level.org.springframework=INFO
spring.output.ansi.enabled = ALWAYS

################### DataSource Configuration ##########################
jdbc:mysql://localhost:3307/paymybuddy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=poseidon_app
spring.datasource.password=Poseidon2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

################### Hibernate Configuration ##########################

#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/poseidon?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.jpa.properties.jakarta.persistence.jdbc.user=poseidon_app
#spring.jpa.properties.jakarta.persistence.jdbc.password=Poseidon2026

