
logging.level.org.springframework=INFO
spring.output.ansi.enabled = ALWAYS

################### DataSource Configuration ##########################
spring.datasource.poseidon.url=jdbc:mysql://localhost:3307/poseidon?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.poseidon.username=poseidon
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

################### Hibernate Configuration ##########################
spring.jpa.hibernate.ddl-auto=validate
# dit à Hibernate d'utiliser les noms de colonnes tels quels (ceux définis dans @Column(name = ...)) au lieu de les convertir en snake_case.
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.show-sql=true

################### ACTUATOR ######################
#(OWASP A05)
management.endpoints.web.exposure.include=health 